### ISSUE TITLE
Mumudvb webservices 

### ISSUE THREAD

**Issue by larbi1** [OPENevents/OE-IPTV#1]
Hi

Is it possible to add Mumudvb webservices (https://github.com/braice/MuMuDVB/blob/master/doc/WEBSERVICES.txt) on OE-IPTV ?

It has already an php file example on https://github.com/braice/MuMuDVB/blob/master/doc/cam_menu.php

Regards

**Comment by novonet** [comment]
Hello,

I've installed OP-IPTV and try to add transponders and i got the following error:

An Error Was Encountered
Unable to load the requested language file: language/french/form_validation_lang.php

how can i fix this issue,
thanks in advance

Bets regards

**Comment by Infobarra** [comment]
Hi 

i have installed OE-IPTV and have errors on displaying PHP pages  when i click transponders or any other links it gives me the following errors

`tuner_id): ?> tuner_id; ?>
 	Nom	IP multicast	Num service	PIDs	Actions
tuner_id]['is_active'] != 1) { echo ""; } else { echo ""; } ?>	
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: item

Filename: chaine/index.php

Line Number: 60

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: chaine/index.php

Line Number: 60

http://177.23.185.16/oeiptv/index.php/tuner/view">
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: item

Filename: chaine/index.php

Line Number: 60

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: chaine/index.php

Line Number: 60

      Num carte :
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: item

Filename: chaine/index.php

Line Number: 62

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: chaine/index.php

Line Number: 62

- Freq :
A PHP Error was encountered

Severity: Notice

Message: Undefined variable: item

Filename: chaine/index.php

Line Number: 63

A PHP Error was encountered

Severity: Notice

Message: Trying to get property of non-object

Filename: chaine/index.php

Line Number: 63`

**Comment by Infobarra** [comment]
Is this compatible with mumudvb 2.0 ?

**Comment by gmarsay** [comment]
@novonet @Infobarra : https://github.com/OPENevents/OE-IPTV/commit/a3d557a575099ecf7ddc9b379e4e20ec4942c918
